lexik_jwt_authentication:
    public_key: '%env(file:resolve:JWT_PUBLIC_KEY)%'
    secret_key: '%env(file:resolve:JWT_SECRET_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: '%env(resolve:JWT_TOKEN_TTL)%'
